services:
  verdaccio:
    image: verdaccio/verdaccio:6.1.6
    ports:
      - "4873:4873"
    volumes:
      - ./verdaccio/config.yaml:/verdaccio/conf/config.yaml:ro
      - verdaccio-storage:/verdaccio/storage

volumes:
  verdaccio-storage:
