storage: /verdaccio/storage

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@ai-supply-chain-fixtures/*':
    access: $all
    publish: $all
    unpublish: $all

  '**':
    access: $all
    proxy: npmjs

server:
  keepAliveTimeout: 60

logs:
  - { type: stdout, format: pretty, level: http }
